package com.academicdashboard.backend.calendar;

import java.util.List;

import org.bson.types.ObjectId; //MongoDB ObjectId (AutoGenerated)
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.DocumentReference;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Document(collection = "calendar")
@Getter
@Setter
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
public class Calendar {

    @Id
    private ObjectId id; //MongoDB ObjectId
    
    private String calendarName;
    private String description;

    //Data Relationship
    @DocumentReference
    private List<Event> events;

    //Constructor: User first creates a calendar (Called by PUT Method)
    public Calendar(String calendarName, String description) {
        this.calendarName = calendarName;
        this.description = description;
    }
}
