package com.academicdashboard.backend.calendar;

import java.util.List;

import org.bson.types.ObjectId; //MongoDB ObjectId (AutoGenerated)
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Document(collection = "event")
@Getter
@Setter
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
public class Event {

    @Id
    private ObjectId id; //MongoDB ObjectId

    //Event Details 
    private String eventTitle;
    private String description;
    private String location;
    private boolean isAllDay; 

    //Repeating Details 
    private String isRecurring;
    private List<String> rptDays; //Repeating Days

    //Date & Time Details
    private String startDate;
    private String lastDate; //Same date for one-time events
    private String startTime;
    private String endTime;
    private int eventLength; //Figure out unit measurment

    //Calendar that event belongs too
    private String calendar;
}
