package com.academicdashboard.backend.checklist;

import java.util.List;

import org.bson.types.ObjectId; //MongoDB ObjectId (AutoGenerated)
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.DocumentReference;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Document(collection = "grouplist")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Grouplist {

    @Id
    private ObjectId id; //MongoDB ObjectId

    //Grouplist's Details
    private String groupId;
    private String title;

    @DocumentReference
    private List<Checklist> checklists;
}
