package com.academicdashboard.backend.reminder;

import org.bson.types.ObjectId; //MongoDB ObjectId (AutoGenerated)
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Document(collection = "reminder")
@Getter
@Setter
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
public class Reminder {

    @Id
    private ObjectId id; //MongoDB ObjectId

    //Reminder Details
    private String content; //Actual Reminder
    private String remindDate;
    private String remindTime;

    private boolean isComplete;
    private boolean isPastDue;

    //Constructor: Each time User creates a new Reminder (Called by PUT Method)
    public Reminder(String content, String remindDate, String remindTime) {
        this.content = content;
        this.remindDate = remindDate;
        this.remindTime = remindTime;
    }
}
