package com.academicdashboard.backend.course;

import java.util.List;

import org.bson.types.ObjectId; //MongoDB ObjectId (AutoGenerated)
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.DocumentReference;

import com.academicdashboard.backend.user.User;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Document(collection = "course")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Course {

    @Id
    private ObjectId id; //MongoDB ObjectId
    
    //Course Details
    private String crsDept; //Course Department
    private String crsTitle; //Course Title
    private String crsNum; //Course Number
    private String crsSection; //Course Section

    //Professor Information
    private String instructor;
    private ObjectId instructorId;

    //Date, Time, & Lecture
    private String firstDate;
    private String lastDate;
    private String semester;
    private int schoolYr;
    private List<LectureHrs> lecture;

    //Data Relationships
    @DocumentReference
    private List<User> students;

    @DocumentReference
    private List<Syllabus> syllabusSection;

    @DocumentReference
    private List<Assignment> assignments;

    @DocumentReference
    private List<Exam> exams;

    @DocumentReference
    private List<Announcement> announcement;
}
